#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'user',
  :git => 'git://github.com/fnichol/chef-user.git'

cookbook 'apache2', '>= 1.0.0'

cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm'
cookbook 'rvm_passenger',
  :git => 'https://github.com/fnichol/chef-rvm_passenger'
cookbook 'chef-postgresql',
   :git => 'https://github.com/coroutine/chef-postgresql'

cookbook 'imagemagick'
cookbook 'nodejs'

cookbook 'chef-rack_stack',
  :git => 'https://github.com/newcontext/chef-rack_stack'

cookbook 'redisio',
  :git => 'https://github.com/brianbianco/redisio.git'

cookbook 'memcached',
  :git => 'http://github.com/opscode-cookbooks/memcached'
