#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apache2', '>= 1.0.0'

cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm'
cookbook 'rvm_passenger',
  :git => 'https://github.com/fnichol/chef-rvm_passenger'
cookbook 'chef-postgresql',
   :git => 'https://github.com/coroutine/chef-postgresql'

cookbook 'imagemagick'
cookbook 'nodejs'

cookbook 'chef_rails_app',
  :git => 'https://github.com/mohangk/chef_rails_app',
  :path => 'site-cookbooks/rails_app'
