#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'


# cookbook 'chef-client'

cookbook 'apache2', '>= 1.0.0'

cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm'
cookbook 'rvm_passenger',
  :git => 'https://github.com/fnichol/chef-rvm_passenger'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
